version: "3"

services:
  db.local:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./env_files/local.env
    restart: unless-stopped
  
  django.local:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
      - static-vol:/app/staticfiles
    command: >
      sh -c "
      # python manage.py reset_db --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
        "
    depends_on:
      - redis.local
      - db.local
    env_file: ./env_files/local.env

  beat.local:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
      - static-vol:/app/staticfiles
    command: >
      sh -c "
        celery -A core beat -l info"
    depends_on:
      - django.local
      - redis.local
    env_file: ./env_files/local.env

  worker.local:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/app
      - static-vol:/app/staticfiles
    command: >
      sh -c "
        celery -A core worker -l info
        "
    depends_on:
      - django.local
      - redis.local
    env_file: ./env_files/local.env

  redis.local:
    image: redis
    entrypoint:
      [
        "sh",
        "-c",
        "redis-server --save '' --appendonly no & sleep 5 && redis-cli -h localhost FLUSHDB && redis-cli -h localhost FLUSHALL && tail -f /dev/null",
      ]
    restart: unless-stopped

  nginx.local:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf

    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - django.local

volumes:
  postgres_data: {}
  static-vol: {}
