# Generated by Django 5.2.1 on 2025-05-27 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'code',
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit numeric password.')
                        ],
                    ),
                ),
                ('is_used', models.BooleanField(default=False, help_text='Indicates if the OTP has been used')),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                (
                    'password',
                    models.CharField(
                        help_text='Enter a 6-digit numeric password.',
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit numeric password.')
                        ],
                        verbose_name='password',
                    ),
                ),
                ('date_of_birth', models.DateField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
