# Generated by Django 5.2.1 on 2025-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='number_of_wallets',
            field=models.IntegerField(default=1, help_text='Number of wallets allowed for this tier'),
        ),
    ]
