# Generated by Django 5.2.1 on 2025-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_tier_number_of_wallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='number_of_wallets',
            field=models.IntegerField(default=5, help_text='Number of wallets allowed for this tier'),
        ),
    ]
