# Generated by Django 5.2.1 on 2025-05-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_tier_number_of_wallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='limits',
        ),
    ]
